openapi: 3.0.0

info:
  title: delilah-resto
  description: Descripcion para almacenar los Endpoints.
  version: 1.0.0
  
servers:
- url: /v1

tags:
  - name: Auth
  - name: User
  - name: Dishes
  - name: Orders

paths:
  /login:
    get:
      summary: Obtiene el token
      description: Pasa al Query los argumentos de usuario y contraseña
      tags:
        - Auth
      parameters:
        - in: query
          name: username
          schema:
            type: string
            example: queen_freddie
          required: true
        - in: query
          name: password
          schema:
            type: string
            format: password
            example: my_personal_password
          required: true
      responses:
        200:
          description: OK
          content:    
            application/json:
              schema:
                $ref: '#/components/schemas/token'
        401:
          description: Usuario y contraseña invalidos
  /users:
    get:
      summary: Retorna todos los usuarios
      description: Solo el administrador puede solicitar consulta
      tags:
        - User
      security: 
        - bearerAuth: []
      responses:
        201:
          description: Created
          content:    
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/user'    
        401:
          $ref: '#/components/responses/UnauthorizedError'
    post:
      summary: Crea un nuevo usuario
      description: Crea un nuevo objeto pasando el objeto correspodiente al body
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_new'
      responses:
        201:
          description: Created
          content:    
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        400:
          description: Informacion incorrecta
  /users/{id}:
    get:
      summary: Trae la información del usuario
      description: Solo los administradores pueden traer la informacion, los usuario solo les permite ver la informacion propia.
      tags:
        - User
      security: 
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          description: User's ID
          required: true
          schema:
            type: integer
            example: 512
      responses:
        200:
          description: Ok
          content:    
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        401:
          $ref: '#/components/responses/UnauthorizedError'
    put:
      summary: Actualiza información del usuario
      description: Solo los administradores la pueden editar.
      tags:
        - User
      security: 
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          description: ID de usuario
          required: true
          schema:
            type: integer
            example: 512
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user_new'
      responses:
        200:
          description: Ok
          content:    
            application/json:
              schema:
                $ref: '#/components/schemas/user_min'
        401:
          $ref: '#/components/responses/UnauthorizedError'
    delete:
      summary: Eliminar usuario
      description: Solo los administradores pueden eliminar está informacion
      tags:
        - User
      security: 
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          description: ID de usuario
          required: true
          schema:
            type: integer
            example: 512
      responses:
        204:
          description: Usuario ha sido eliminado.
        401:
          $ref: '#/components/responses/UnauthorizedError'
  /users/{id}/dishes:
    get:
      summary: Obtiene los platos favoritos
      description: Retornara todos los platos ordenados por cantidad consumida
      tags:
        - Dishes
      security: 
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          description: Usuario ID
          required: true
          schema:
            type: integer
            example: 512
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/dish_accum'
        401:
          $ref: '#/components/responses/UnauthorizedError'
  /dishes:
    get:
      summary: Obtiene toda la informacion de los platos
      tags:
        - Dishes
      security: 
        - bearerAuth: []
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/dish'
        401:
          $ref: '#/components/responses/UnauthorizedError'
    post:
      summary: Crea un nuevo plato
      tags:
        - Dishes
      security: 
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dish_min'
      responses:
        201:
          description: El plato ha sido creado!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dish'
        401:
          $ref: '#/components/responses/UnauthorizedError'
  /dishes/{id}:
    get:
      summary: Obtiene un nuevo plato
      tags:
        - Dishes
      security: 
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          description: Obtiene el ID del plato
          required: true
          schema:
            type: integer
            example: 666
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dish'
        401:
          $ref: '#/components/responses/UnauthorizedError'
    put:
      summary: Modifica la informacion del plato
      tags:
        - Dishes
      security: 
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          description: ID del plato
          required: true
          schema:
            type: integer
            example: 666
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dish_min'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dish'
        401:
          $ref: '#/components/responses/UnauthorizedError'
    delete:
      summary: Elimina el plato
      tags:
        - Dishes
      security: 
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          description: Dish's ID
          required: true
          schema:
            type: integer
            example: 666
      responses:
        204:
          description: Plato fue eliminado.
        401:
          $ref: '#/components/responses/UnauthorizedError'
  /orders:
    get:
      summary: Retorna todas las ordenes dependien de los parametros
      description: Si no se especifica ningún parámetro, se recuperarán los pedidos del día actual. Los filtros antes y después juntos y "en" agregan la fecha al resultado del filtro
      tags:
        - Orders
      parameters:
        - in: query
          name: at
          description: Filtrar pedidos según la fecha ISO exacta
          example: "2020-06-15"
          required: false
          schema:
            type: string
            format: date
        - in: query
          name: before
          description: Filtrar pedidos anteriores o iguales a la fecha ISO.
          example: "2020-04-15"
          required: false
          schema:
            type: string
            format: date
        - in: query
          name: after
          description: Filtrar pedidos posteriores o iguales a la fecha ISO.
          example: "2020-01-01"
          required: false
          schema:
            type: string
            format: date
      security: 
        - bearerAuth: []
      responses:
        201:
          description: Array of orders.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/order'
        401:
          $ref: '#/components/responses/UnauthorizedError'
    post:
      summary: Crear un nuevo pedido para la usuaria
      description: La identificación del usuario se encontrará dentro del token, por lo que no es necesario
      tags:
        - Orders
      security: 
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/order_new'
      responses:
        201:
          description: Created
          content:    
            application/json:
              schema:
                $ref: '#/components/schemas/order'
        401:
          $ref: '#/components/responses/UnauthorizedError'
  /orders/{id}:
    get:
      summary: Get order info
      tags:
        - Orders
      security: 
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          description: Order ID
          required: true
          schema:
            type: integer
            example: 36
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
        401:
          $ref: '#/components/responses/UnauthorizedError'
    put:
      summary: Actualizar el estado del pedido
      tags:
        - Orders
      security: 
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          description: Order ID
          required: true
          schema:
            type: integer
            example: 36
        - in: query
          name: state
          description: Nuevo estado del pedido
          example: 2
          required: true
          schema:
            type: number
      responses:
        201:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
        401:
          $ref: '#/components/responses/UnauthorizedError'
components:
  schemas:
    token:
      type: object
      properties:
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEyMzQ1Njc4OTAiLCJpYXQiOjE1MTYyMzkwMjJ9.C7eecdX_pumR-P1Kv3q3fkp27Jtian0VJKy4XpStmt8
    user_min:
      type: object
      properties:
        full_name:
          type: string
          example: Freddie Mercury
        username:
          type: string
          example: queen_freddie
        email:
          type: string
          example: freddiemercury@gmail.com
        phone:
          type: string
          example: +447712345678
        address:
          type: string
          example: Maipu 999 1º A
    user_new:
      allOf:
        - $ref: "#/components/schemas/user_min"
        - type: object
          properties:
            password:       # Contraseña requerida
              type: string
              example: my_personal_password
    user:
      allOf:
        - type: object
          properties:
            id:             # id numerico adicionado
              type: number
              example: 5487
        - $ref: '#/components/schemas/user_min'
        - type: object
          properties:
            id_security_type: # admin / usuario
              type: number
              example: 1
    dish_new:
      type: object
      properties:
        id:
          type: number
          example: 15
        quantity:
          type: number
          example: 3
    dish_min:
      type: object
      properties:
        name:
          type: string
          example: Hamburguesa Clásica
        name_short:
          type: string
          example: HamClas
        description:
          type: string
          example: Hamburguesa 200g de carne, con lechuga y tomate.
        price:
          type: number
          example: 350
        img_path:
          type: string
          example: ./src/img/ham-clas.png
        is_available:
          type: boolean
          example: true     
    dish:
      allOf:
        - type: object
          properties:
            id:
              type: number
              example: 666
        - $ref: "#/components/schemas/dish_min"
    dish_accum:
      allOf:
        - type: object
          properties:
            dish:
              $ref: '#/components/schemas/dish'
        - type: object  
          properties:
            accumulated:
              type: number
              example: 20
              description: Number of times the user's requested dish.
    ordered_dishes:
      type: array
      items:
        allOf:
          - type: object
            properties:
              dish:
                $ref: '#/components/schemas/dish'
          - type: object  
            properties:
              ordered:
                type: number
                example: 3
                description: Numero de plato pedido

              purchased_price:
                type: number
                example: 250
                description: Precio en el que se compró el plato
              subtotal:
                type: number
                example: 750
                description: Subtotal comprado.
    order_new:
      type: object
      properties:
        dishes:
          type: array
          items:
            $ref: "#/components/schemas/dish_new"
        payment_type:
          type: number
          example: 2
        address:
          type: string
          example: Montevideo 1212 1B
    order:
      type: object
      properties:
        id:
          type: number
          example: 5412
        number:
          type: integer
          example: 500
        address:
          type: string
          example: Montevideo 1212 1B
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        description:
          type: string
          example: 1xHamClas 1xSandVegg
        status:
          type: array
          items:
            type: object
            properties:
              status:
                type: string
                example: En Preparaciòn
              timestamp:
                type: string
                format: date-time
        user:
          $ref: "#/components/schemas/user"
        payment:
          type: object
          properties:
            type:
              type: number
              example: 2
            total:
              type: number
              example: 650
        dishes:
          $ref: "#/components/schemas/ordered_dishes"

  responses:
    UnauthorizedError:
      description: Acceso al token se ha perdido o invalido      
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT   